// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkZCp7-ILPeLokQHLjKsms0-7uPdBDWmc',
    appId: '1:844348610557:web:2e83815ff7bfdf95a1ab94',
    messagingSenderId: '844348610557',
    projectId: 'chefistant',
    authDomain: 'chefistant.firebaseapp.com',
    storageBucket: 'chefistant.appspot.com',
    measurementId: 'G-6CSQLRFLXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgLkYUDbYNxranXXAjUIXC00s24dRwQQc',
    appId: '1:844348610557:android:f763dec3990a5f8ca1ab94',
    messagingSenderId: '844348610557',
    projectId: 'chefistant',
    storageBucket: 'chefistant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZB62zbUyWT0QhqyXsS-ua2WVOw611IqM',
    appId: '1:844348610557:ios:257348f6725a6592a1ab94',
    messagingSenderId: '844348610557',
    projectId: 'chefistant',
    storageBucket: 'chefistant.appspot.com',
    iosBundleId: 'com.example.chefistantFoodRecipeHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZB62zbUyWT0QhqyXsS-ua2WVOw611IqM',
    appId: '1:844348610557:ios:6b8d045fcf43743da1ab94',
    messagingSenderId: '844348610557',
    projectId: 'chefistant',
    storageBucket: 'chefistant.appspot.com',
    iosBundleId: 'com.example.chefistantFoodRecipeHelper.RunnerTests',
  );
}
